version: '3.8'

services:
    
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:13
    container_name: laricroche_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local
