version: '3.8'

services:
  # Serviço da API Go
  api:
    image: golang:1.23 # Use a versão de Golang que você está usando
    container_name: laricroche_api
    working_dir: /go/src/app
    volumes:
      - .:/go/src/app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST={DB_HOST}
      - DB_USER={DB_USER}
      - DB_PASSWORD={DB_PASSWORD}
      - DB_NAME={DB_NAME}
      - DB_PORT={DB_PORT}
      - JWT_SECRET={JWT_SECRET}
    depends_on:
      - db
    command: ["go", "run", "cmd/main.go"]
    
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:13
    container_name: laricroche_db
    environment:
      POSTGRES_USER: {DB_USER}
      POSTGRES_PASSWORD: {DB_PASSWORD}
      POSTGRES_DB: {DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local
